CREATE TABLE ATTRIBUTE (
  ID   INT PRIMARY KEY NOT NULL,
  NAME TEXT            NOT NULL
);

CREATE TABLE BROWSER (
  ID      INT PRIMARY KEY  NOT NULL,
  NAME    TEXT             NOT NULL,
  VERSION VARCHAR(10)      NOT NULL
);

CREATE TABLE SUPPORTED_STATUS (
  ID   INT PRIMARY KEY  NOT NULL,
  NAME VARCHAR(10)--FULL, PARTIAL, NOT
);

CREATE TABLE BROWSER_TO_ATTRIBUTE (
  BROWSER_ID          INT NOT NULL,
  ATTRIBUTE_ID        INT NOT NULL,
  SUPPORTED_STATUS_ID INT NOT NULL
);

ALTER TABLE BROWSER_TO_ATTRIBUTE
  ADD CONSTRAINT BROWSER_ID_FK FOREIGN KEY (BROWSER_ID) REFERENCES BROWSER (ID);
ALTER TABLE BROWSER_TO_ATTRIBUTE
  ADD CONSTRAINT ATTRIBUTE_ID_FK FOREIGN KEY (ATTRIBUTE_ID) REFERENCES ATTRIBUTE (ID);
ALTER TABLE BROWSER_TO_ATTRIBUTE
  ADD CONSTRAINT SUPPORTED_STATUS_ID_FK FOREIGN KEY (SUPPORTED_STATUS_ID) REFERENCES SUPPORTED_STATUS (ID);