CREATE TABLE ATTRIBUTE (
  ID   INT PRIMARY KEY NOT NULL,
  NAME TEXT            NOT NULL
);

CREATE TABLE BROWSER (
  ID      INT PRIMARY KEY  NOT NULL,
  NAME    TEXT             NOT NULL,
  VERSION VARCHAR(10)      NOT NULL
);

CREATE TABLE SUPPORTED_STATUS (
  ID     INT PRIMARY KEY  NOT NULL,
  STATUS VARCHAR(10)--FULL, PARTIAL, NOT
);


CREATE TABLE BROWSER_TO_ATTRIBUTE (
  ID           INT PRIMARY KEY  NOT NULL,
  BROWSER_ID   INT              NOT NULL,
  ATTRIBUTE_ID INT              NOT NULL
);

CREATE TABLE BROWSER_TO_ATTRIBUTE_STATUS (
  BROWSER_TO_ATTRIBUTE_ID INT PRIMARY KEY  NOT NULL,
  SUPPORTED_STATUS_ID     INT              NOT NULL
);

ALTER TABLE BROWSER_TO_ATTRIBUTE
  ADD CONSTRAINT BROWSER_ID_FK FOREIGN KEY (BROWSER_ID) REFERENCES BROWSER (ID);
ALTER TABLE BROWSER_TO_ATTRIBUTE
  ADD CONSTRAINT ATTRIBUTE_ID_FK FOREIGN KEY (ATTRIBUTE_ID) REFERENCES ATTRIBUTE (ID);

ALTER TABLE BROWSER_TO_ATTRIBUTE_STATUS
  ADD CONSTRAINT BROWSER_TO_ATTRIBUTE_ID_FK FOREIGN KEY (BROWSER_TO_ATTRIBUTE_ID) REFERENCES BROWSER_TO_ATTRIBUTE (ID);
ALTER TABLE BROWSER_TO_ATTRIBUTE_STATUS
  ADD CONSTRAINT SUPPORTED_STATUS_ID_FK FOREIGN KEY (SUPPORTED_STATUS_ID) REFERENCES SUPPORTED_STATUS (ID);
